(function(l){var g=l.document,h=l.navigator,b={version:"0.1.0",e:"auto"};b.g=b.g||{};b.g.C=function(){};b.a=b.a||{};b.a.aa=function(a,d){this.host=a;this.$=d};b.a.hash=function(a){var d=1,c=0,e;if(!b.a.f(a)){d=0;for(e=a.length-1;e>=0;e--){c=a.charCodeAt(e);d=(d<<6&268435455)+c+(c<<14);c=d&266338304;d=c!=0?d^c>>21:d}}return d};b.a.indexOf=function(a,d){return a.indexOf(d)};b.a.i=function(a,d){return b.a.indexOf(a,d)>-1};b.a.r=function(a){return a.length>0&&b.a.i(" \n\r\t",a)};b.a.f=function(a){return undefined==
a||"-"==a||""==a};b.a.substring=function(a,d,c){c=undefined==c?a.length:c;return a.substring(d,c)};b.a.s=function(a){return a.toLowerCase()};b.a.split=function(a,d){return a.split(d)};b.a.k=function(a){if(!a||""==a)return"";for(;b.a.r(a.charAt(0));)a=a.substring(1);for(;b.a.r(a.charAt(a.length-1));)a=a.substring(0,a.length-1);return a};b.a.Z=function(a){var d=false,c=0,e,f;if(!b.a.f(a)){d=true;for(e=0;e<a.length;e++){f=a.charAt(e);c+="."==f?1:0;d=d&&c<=1&&(0==e&&"-"==f||b.a.i(".0123456789",f))}}return d};
b.a.X=function(a,d,c){var e="-",f;if(!b.a.f(a)&&!b.a.f(d)&&!b.a.f(c)){f=b.a.indexOf(a,d);if(f>-1){c=a.indexOf(c,f);if(c<0)c=a.length;e=b.a.substring(a,f+b.a.indexOf(d,"=")+1,c)}}return e};b.a.d=function(a,d){var c=encodeURIComponent;return c instanceof Function?d?encodeURI(a):c(a):escape(a)};b.a.V=function(a,d){var c=decodeURIComponent,e;a=a.split("+").join(" ");if(c instanceof Function)try{e=d?decodeURI(a):c(a)}catch(f){e=unescape(a)}else e=unescape(a);return e};b.a.u=function(){return Math.round(Math.random()*
2147483647)};b.a.q=function(){if(h.userAgent.indexOf("MSIE")>0)return"MSIE";else if(h.userAgent.indexOf("Firefox")>0)return"Firefox";else if(h.userAgent.indexOf("Safari")>0)return"Safari";else if(h.userAgent.indexOf("Chrome")>0)return"Chrome";else if(h.userAgent.indexOf("Camino")>0)return"Camino";else if(h.userAgent.indexOf("Gecko/")>0)return"Gecko";return"Other"};b.c=b.c||{};b.c.D=function(){var a,d,c;a=g.cookie?g.cookie:"";d=l.history.length;c=[h.appName,h.version,h.language?h.language:h.n,h.platform,
h.userAgent,h.javaEnabled()?1:0].join("");if(l.screen)c+=l.screen.width+"x"+l.screen.height+l.screen.colorDepth;else if(l.java)try{var e=java.awt.Toolkit.getDefaultToolkit().getScreenSize();c+=e.screen.width+"x"+e.screen.height}catch(f){}c+=a;c+=g.referrer?g.referrer:"";for(a=c.length;d>0;)c+=d--^a++;return b.a.hash(c)};b.c.U=function(){return(b.a.u()^b.c.D())*2147483647};b.c.N=function(a,d){var c="jsonp"+(new Date).getTime()+Math.floor(Math.random()*1E4);a=a+"&cb="+c;l[c]=l[c]||function(k){data=
k;typeof d=="function"&&d(data);l[c]=undefined;try{delete l[c]}catch(m){}e&&e.removeChild(f)};var e=g.getElementsByTagName("head")[0]||g.documentElement,f=g.createElement("script");f.src=a;e.insertBefore(f,e.firstChild)};b.c.I=function(){var a,d=h?h.plugins:undefined,c;if(d&&d.length>0)for(var e=0;e<d.length&&!c;e++){a=d[e];if(b.a.i(a.name,"Shockwave Flash"))c=b.a.split(a.description,"Shockwave Flash ")[1]}else{try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");c=a.p("$version")}catch(f){}if(!c)try{a=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");c="WIN 6,0,21,0";a.Y="always";c=a.p("$version")}catch(k){}if(!c)try{a=new ActiveXObject("ShockwaveFlash.ShockwaveFlash");c=a.p("$version")}catch(m){}if(c){c=b.a.split(b.a.split(c," ")[1],",");c=c[0]+"."+c[1]+" r"+c[2]}}return c?c:"-"};b.c.lang=function(){return b.a.s(h&&h.language?h.language:h.n?h.n:"-")};b.c.O=function(){return h&&h.javaEnabled()?1:0};b.c.charset=function(){return b.a.d(g.characterSet?g.characterSet:g.charset?g.charset:"-")};b.c.S=
function(){if(self.screen)return screen.width+"x"+screen.height;else if(this.R)try{var a=this.R.T();return a.width+"x"+a.height}catch(d){}return"-"};b.c.H=function(){if(self.screen)return screen.colorDepth+"-bit";return"-"};b.c.w=function(){return"&"+["ucs="+b.a.d(b.c.charset()),"usr="+b.c.S(),"uco="+b.c.H(),"ula="+b.c.lang(),"uj="+b.c.O(),"uf="+b.a.d(b.c.I())].join("&")};b.b=b.b||{};b.b.t=function(){return"file:"!=g.location.protocol};b.b.L=function(){if("auto"==b.e){var a=g.domain;if("www."==b.a.substring(a,
0,4))a=b.a.substring(a,4);b.e=a}b.e=b.a.s(b.e)};b.b.W=function(){if(!b.e||""==b.e||"none"==b.e){b.e="";return 1}b.b.L();return b.a.hash(b.e)};b.b.Q=function(a){return a=a||g.location.pathname+g.location.search};b.b.K=function(){var a=g.referrer,d=g.domain;if(b.a.f(a))a="-";else{d+="/";d=b.a.indexOf(a,d);a=d>=0&&d<=8?"0":"["==a.charAt(0)&&"]"==a.charAt(a.length-1)?"-":a}return a};b.b.F=function(a){var d=b.c.w();d+=!b.a.f(g.title)?"&ut="+b.a.d(b.a.k(g.title)):"";d+="&ure="+b.a.d(b.b.K())+"&uh="+b.a.d(g.location.hostname)+
"&up="+b.a.d(b.b.Q(a));return d};b.b.l=function(a,d,c){var e="?uv="+b.version+"&ur="+b.a.u()+b.b.F(a);a="";if(c!=undefined&&c!=null)e+=c;a="https:"==g.location.protocol?"https://secure.uctrac.com/js/1x1.gif"+e:"http://t.uctrac.com/js/1x1.gif"+e;if(d)b.c.N(a,function(){});else{d=new Image(1,1);d.src=a;d.onload=b.g.C}};b.b.o=function(a,d,c){return function(){var e="&ua=hook";if(d!=undefined&&d!=null&&d!="null"){var f=d.split(",");for(var k in f){var m=f[k];if(m!=""){attr_val=b.a.q()=="MSIE"?a.getAttributeNode(m).value:
a.getAttribute(m);e+="&ua"+m+"="+b.a.d(b.a.k(attr_val))}}}if(a.value!=undefined)e+="&uaval="+b.a.d(b.a.k(a.value));b.b.l(c,false,e)}};b.b.A=function(a,d,c,e){for(var f=0;f<a.length;f++)if(g.addEventListener)a[f].addEventListener(d,b.b.o(a[f],c,e),true);else g.attachEvent&&a[f].attachEvent("on"+d,b.b.o(a[f],c,e))};b.b.getElementsByClassName=function(a,d){d||(d=g);if(b.a.q()=="MSIE"){var c=[],e=d.getElementsByTagName("*"),f=e.length,k=RegExp("(^|\\s)"+a+"(\\s|$)");for(j=i=0;i<f;i++)if(k.test(e[i].className)){c[j]=
e[i];j++}return c}return d.getElementsByClassName(a)};b.b.j=function(a){for(var d=Array(a.length),c=0;c<a.length;c++)d[c]=a[c];return d};b.b.h=function(a,d){if(typeof a!=="string"){if(typeof a.nodeType==="number")return[a];if(typeof a.length==="number")return b.b.j(a);return[]}if(a.charAt(0)==="$")try{return b.b.h(eval(a.substr(1)))}catch(c){return[]}d||(d=g);for(var e=a.split(/\s+/),f=[d],k=0;k<e.length;k++){for(var m=e[k],n=[],o=0;o<f.length;o++)n=n.concat(b.b.J(m,f[o]));f=n}return n};b.b.J=function(a,
d){if(a.charAt(0)==="#"){var c=g.getElementById(a.substr(1));if(c==null)return[];return[c]}else if(a.charAt(0)===".")return b.b.j(b.b.getElementsByClassName(a.substr(1),d));else if(a.indexOf("#")>0){var e=a.split("#"),f=e[0],k=e[1];e=[];for(var m=d.getElementsByTagName(f),n=0;n<m.length;n++){c=m[n];c.getAttribute("id")==k&&e.push(c)}return e}else if(a.indexOf(".")>0){e=a.split(".");f=e[0].toLowerCase();c=e[1];e=[];m=b.b.getElementsByClassName(c,d);for(n=0;n<m.length;n++){c=m[n];c.tagName.toLowerCase()==
f&&e.push(c)}return e}return b.b.j(d.getElementsByTagName(a))};b.b.z=function(a,d,c,e){a=b.b.h(a);a!=null&&b.b.A(a,d,c,e)};b.b.P=function(a){if(!a)for(var d=[[/\x61if\x61ng\.\x63om$/,"162976"],[/\x7an\x7a8\x388\.\x63n$/,"162977"]],c=0;c<d.length;c++){var e=d[c];if(e[0].test(g.location.hostname)){a="retarget_"+e[1];break}}if(b.b.t())b.b.l(null,false,a?"&un="+b.a.d(a):"")};b.b.m=function(a,d,c,e){b.b.t()&&b.b.z(a,d,c,e)};b.b.B=function(a,d,c,e){var f={v:0};f.id=setInterval(function(){f.v>300&&clearInterval(f.id);
try{if(b.b.h(a).length!=0){b.b.m(a,d,c,e);clearInterval(f.id)}else f.v++}catch(k){}},200)};b.b.G=function(a){var d=""+g.referrer,c=""+l.location.href;a+="=";var e=c.indexOf("?"),f="";if(e!=-1){e=c.substring(e+1).split("&");for(var k=0;k<e.length;k++)if(e[k].substr(0,a.length)==a){f=e[k].substr(a.length);break}}if(f==="")f=Math.floor(Math.random()*Math.pow(2,20)).toString(16)+(new Date).getTime().toString(16);e="http://t.uctrac.com/js/1x1.gif?tp=ltjrecmgk";e+="&src="+b.a.d(d);e+="&dst="+b.a.d(c);e+=
"&"+a+f;a=new Image(1,1);a.src=e;a.onload=function(){};return f};b.b.M=function(){var a=g.createElement("iframe");a.style.display="none";try{g.getElementsByTagName("head")[0].appendChild(a);a.src="http://www.uctrac.com/m.htm"}catch(d){}};l.$uctrac=b;b.logConv=b.b.P;b.attach=b.b.m;b.attach_wait=b.b.B;b.clickId=b.b.G;b.init=b.b.M})(window);
